# Generated by Django 5.0.1 on 2026-07-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='phone',
            field=models.CharField(blank=True, help_text='WhatsApp do convidado (com DDD, ex: 11999999999)', max_length=20),
        ),
    ]
