# Generated by Django 5.0.1 on 2026-06-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Escuro'), ('light', 'Claro')], default='dark', help_text='Tema da interface (escuro ou claro).', max_length=5)),
                ('results_limit', models.PositiveIntegerField(default=20, help_text='Limite padrão de resultados exibidos pela IA.')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
