# Generated by Django 5.0.1 on 2026-07-14 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Configuracao do Site', 'verbose_name_plural': 'Configuracoes do Site'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='results_limit',
            field=models.PositiveIntegerField(default=20, help_text='Limite padrao de resultados exibidos pela IA.'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Escuro'), ('light', 'Claro')], default='dark', max_length=5)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar_color', models.CharField(default='primary', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
