# Generated by Django 5.0.1 on 2026-07-14 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_conversation_chatmessage_conversation'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesult',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tenants.tenant'),
        ),
    ]
